version: '3.8'

services:
  causal-discovery:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./datasets:/app/datasets
    environment:
      - FLASK_ENV=development
    command: python notears_web_gui.py